// Code generated by MockGen. DO NOT EDIT.
// Source: app/usecases/payment_usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "billing-engine/app/models"
	reflect "reflect"
	"testing"

	gomock "github.com/golang/mock/gomock"
)

func TestNewMockPaymentUsecase(t *testing.T) {
	type args struct {
		ctrl *gomock.Controller
	}
	tests := []struct {
		name string
		args args
		want *MockPaymentUsecase
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := NewMockPaymentUsecase(tt.args.ctrl); !reflect.DeepEqual(got, tt.want) {
				t.Errorf("NewMockPaymentUsecase() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestMockPaymentUsecase_EXPECT(t *testing.T) {
	type fields struct {
		ctrl     *gomock.Controller
		recorder *MockPaymentUsecaseMockRecorder
	}
	tests := []struct {
		name   string
		fields fields
		want   *MockPaymentUsecaseMockRecorder
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			m := &MockPaymentUsecase{
				ctrl:     tt.fields.ctrl,
				recorder: tt.fields.recorder,
			}
			if got := m.EXPECT(); !reflect.DeepEqual(got, tt.want) {
				t.Errorf("MockPaymentUsecase.EXPECT() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestMockPaymentUsecase_CreatePayment(t *testing.T) {
	type fields struct {
		ctrl     *gomock.Controller
		recorder *MockPaymentUsecaseMockRecorder
	}
	type args struct {
		LoanID            uint
		totalAmount       float64
		InstallmentNumber int64
	}
	tests := []struct {
		name    string
		fields  fields
		args    args
		want    *models.Payment
		wantErr bool
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			m := &MockPaymentUsecase{
				ctrl:     tt.fields.ctrl,
				recorder: tt.fields.recorder,
			}
			got, err := m.CreatePayment(tt.args.LoanID, tt.args.totalAmount, tt.args.InstallmentNumber)
			if (err != nil) != tt.wantErr {
				t.Errorf("MockPaymentUsecase.CreatePayment() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("MockPaymentUsecase.CreatePayment() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestMockPaymentUsecaseMockRecorder_CreatePayment(t *testing.T) {
	type fields struct {
		mock *MockPaymentUsecase
	}
	type args struct {
		LoanID            interface{}
		totalAmount       interface{}
		InstallmentNumber interface{}
	}
	tests := []struct {
		name   string
		fields fields
		args   args
		want   *gomock.Call
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			mr := &MockPaymentUsecaseMockRecorder{
				mock: tt.fields.mock,
			}
			if got := mr.CreatePayment(tt.args.LoanID, tt.args.totalAmount, tt.args.InstallmentNumber); !reflect.DeepEqual(got, tt.want) {
				t.Errorf("MockPaymentUsecaseMockRecorder.CreatePayment() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestMockPaymentUsecase_GetPaymentsByLoanID(t *testing.T) {
	type fields struct {
		ctrl     *gomock.Controller
		recorder *MockPaymentUsecaseMockRecorder
	}
	type args struct {
		LoanID uint
	}
	tests := []struct {
		name    string
		fields  fields
		args    args
		want    []models.Payment
		want1   int64
		wantErr bool
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			m := &MockPaymentUsecase{
				ctrl:     tt.fields.ctrl,
				recorder: tt.fields.recorder,
			}
			got, got1, err := m.GetPaymentsByLoanID(tt.args.LoanID)
			if (err != nil) != tt.wantErr {
				t.Errorf("MockPaymentUsecase.GetPaymentsByLoanID() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("MockPaymentUsecase.GetPaymentsByLoanID() got = %v, want %v", got, tt.want)
			}
			if got1 != tt.want1 {
				t.Errorf("MockPaymentUsecase.GetPaymentsByLoanID() got1 = %v, want %v", got1, tt.want1)
			}
		})
	}
}

func TestMockPaymentUsecaseMockRecorder_GetPaymentsByLoanID(t *testing.T) {
	type fields struct {
		mock *MockPaymentUsecase
	}
	type args struct {
		LoanID interface{}
	}
	tests := []struct {
		name   string
		fields fields
		args   args
		want   *gomock.Call
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			mr := &MockPaymentUsecaseMockRecorder{
				mock: tt.fields.mock,
			}
			if got := mr.GetPaymentsByLoanID(tt.args.LoanID); !reflect.DeepEqual(got, tt.want) {
				t.Errorf("MockPaymentUsecaseMockRecorder.GetPaymentsByLoanID() = %v, want %v", got, tt.want)
			}
		})
	}
}
