// Code generated by MockGen. DO NOT EDIT.
// Source: app/usecases/payment_usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "billing-engine/app/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPaymentUsecase is a mock of PaymentUsecase interface.
type MockPaymentUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentUsecaseMockRecorder
}

// MockPaymentUsecaseMockRecorder is the mock recorder for MockPaymentUsecase.
type MockPaymentUsecaseMockRecorder struct {
	mock *MockPaymentUsecase
}

// NewMockPaymentUsecase creates a new mock instance.
func NewMockPaymentUsecase(ctrl *gomock.Controller) *MockPaymentUsecase {
	mock := &MockPaymentUsecase{ctrl: ctrl}
	mock.recorder = &MockPaymentUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentUsecase) EXPECT() *MockPaymentUsecaseMockRecorder {
	return m.recorder
}

// CreatePayment mocks base method.
func (m *MockPaymentUsecase) CreatePayment(LoanID uint, totalAmount float64, InstallmentNumber int64) (*models.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", LoanID, totalAmount, InstallmentNumber)
	ret0, _ := ret[0].(*models.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockPaymentUsecaseMockRecorder) CreatePayment(LoanID, totalAmount, InstallmentNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockPaymentUsecase)(nil).CreatePayment), LoanID, totalAmount, InstallmentNumber)
}

// GetPaymentsByLoanID mocks base method.
func (m *MockPaymentUsecase) GetPaymentsByLoanID(LoanID uint) ([]models.Payment, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentsByLoanID", LoanID)
	ret0, _ := ret[0].([]models.Payment)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPaymentsByLoanID indicates an expected call of GetPaymentsByLoanID.
func (mr *MockPaymentUsecaseMockRecorder) GetPaymentsByLoanID(LoanID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentsByLoanID", reflect.TypeOf((*MockPaymentUsecase)(nil).GetPaymentsByLoanID), LoanID)
}
